version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  mariadb:
    image: mariadb:latest
    platform: linux/x86_64
    container_name: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_small_dev
    networks:
      - mariadb_network
    ports:
      - "3306:3306"
  ###< doctrine/doctrine-bundle ###

  ###> adminer ###
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter
    depends_on:
      - mariadb
    ports:
      - "8085:8080"
    networks:
      - mariadb_network
  ###< adminer ###

  ###> MailDev ###
  maildev:
    image: maildev/maildev
    container_name: maildev_small_dev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    # MAILER_DSN=smtp://127.0.0.1:1025
    ports:
      - "8081:80"
      - "1025:25"
    restart: always
    networks:
      - mariadb_network
###< MailDev ###

networks:
  mariadb_network:

volumes:
  db-data:
